# Generated by Django 3.0.5 on 2020-04-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='daily_rate',
            new_name='daily_rental_rate',
        ),
    ]
